// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ldudoytiyovnugmezydr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxkdWRveXRpeW92bnVnbWV6eWRyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgxMTk5NTQsImV4cCI6MjA2MzY5NTk1NH0.pe0yHUZHouxP1etVe850zXDbVF_CirL82n1bXhNc99E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);